In [32]:
import pandas as pd
df=pd.read_csv(r"C:\Users\OWNER\Desktop\VICTOR\python\py-master\ML\18_PCA\Exercise\heart.csv")
df

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [33]:
cholesterol_max=df["Cholesterol"].mean()+3*df["Cholesterol"].std()
cholesterol_min=df["Cholesterol"].mean()-3*df["Cholesterol"].std()

In [34]:
cholesterol_treated=df[(df["Cholesterol"]<cholesterol_max)&(df["Cholesterol"]>cholesterol_min)]
cholesterol_treated

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [35]:
max_hr_max=cholesterol_treated["MaxHR"].mean()+3*cholesterol_treated["MaxHR"].std()
max_hr_min=cholesterol_treated["MaxHR"].mean()-3*cholesterol_treated["MaxHR"].std()

In [36]:
max_hr_treated=cholesterol_treated[(cholesterol_treated["MaxHR"]<max_hr_max)&(cholesterol_treated["MaxHR"]>max_hr_min)]
max_hr_treated

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [37]:
Oldpeak_max=max_hr_treated["Oldpeak"].mean()+3*max_hr_treated["Oldpeak"].std()
Oldpeak_min=max_hr_treated["Oldpeak"].mean()-3*max_hr_treated["Oldpeak"].std()

In [38]:
old_peak_treated=max_hr_treated[(max_hr_treated["Oldpeak"]<Oldpeak_max)&(max_hr_treated["Oldpeak"]>Oldpeak_min)]
old_peak_treated

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [39]:
RestingBP_max=old_peak_treated["RestingBP"].mean()+3*old_peak_treated["RestingBP"].std()
RestingBP_min=old_peak_treated["RestingBP"].mean()-3*old_peak_treated["RestingBP"].std()

In [40]:
RestingBP_treated=old_peak_treated[(old_peak_treated["RestingBP"]<RestingBP_max)&(old_peak_treated["RestingBP"]>RestingBP_min)]
RestingBP_treated

,Age,Sex,ChestPainType,RestingBP,Cholesterol,FastingBS,RestingECG,MaxHR,ExerciseAngina,Oldpeak,ST_Slope,HeartDisease
0,40,M,ATA,140,289,0,Normal,172,N,0.0,Up,0
1,49,F,NAP,160,180,0,Normal,156,N,1.0,Flat,1
2,37,M,ATA,130,283,0,ST,98,N,0.0,Up,0
3,48,F,ASY,138,214,0,Normal,108,Y,1.5,Flat,1
4,54,M,NAP,150,195,0,Normal,122,N,0.0,Up,0
...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,M,TA,110,264,0,Normal,132,N,1.2,Flat,1
914,68,M,ASY,144,193,1,Normal,141,N,3.4,Flat,1
915,57,M,ASY,130,131,0,Normal,115,Y,1.2,Flat,1
916,57,F,ATA,130,236,0,LVH,174,N,0.0,Flat,1
917,38,M,NAP,138,175,0,Normal,173,N,0.0,Up,0

In [41]:
df1=pd.get_dummies(RestingBP_treated,drop_first=True)

In [42]:
df1

,Age,RestingBP,Cholesterol,FastingBS,MaxHR,Oldpeak,HeartDisease,Sex_M,ChestPainType_ATA,ChestPainType_NAP,ChestPainType_TA,RestingECG_Normal,RestingECG_ST,ExerciseAngina_Y,ST_Slope_Flat,ST_Slope_Up
0,40,140,289,0,172,0.0,0,1,1,0,0,1,0,0,0,1
1,49,160,180,0,156,1.0,1,0,0,1,0,1,0,0,1,0
2,37,130,283,0,98,0.0,0,1,1,0,0,0,1,0,0,1
3,48,138,214,0,108,1.5,1,0,0,0,0,1,0,1,1,0
4,54,150,195,0,122,0.0,0,1,0,1,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
913,45,110,264,0,132,1.2,1,1,0,0,1,1,0,0,1,0
914,68,144,193,1,141,3.4,1,1,0,0,0,1,0,0,1,0
915,57,130,131,0,115,1.2,1,1,0,0,0,1,0,1,1,0
916,57,130,236,0,174,0.0,1,0,1,0,0,0,0,0,1,0
917,38,138,175,0,173,0.0,0,1,0,1,0,1,0,0,0,1

In [43]:
x=df1.drop("HeartDisease",axis="columns")
y=df1.HeartDisease

In [44]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_scaled=scaler.fit_transform(x)

In [45]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.2, random_state=30)

In [46]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

In [29]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [48]:
from sklearn.model_selection import RandomizedSearchCV
import pandas as pd

scores = []

for model_name, mp in model_params.items():
    clf = RandomizedSearchCV(mp['model'], mp['params'], n_iter=2, cv=5, return_train_score=False, random_state=42)
    clf.fit(x, y)  # Replace x and y with your actual dataset and target variables
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df_params = pd.DataFrame(scores, columns=['model', 'best_score', 'best_params'])
print(df_params)

                 model  best_score                   best_params
0                  svm    0.828597  {'kernel': 'linear', 'C': 1}
1        random_forest    0.776344           {'n_estimators': 5}
2  logistic_regression    0.834178                      {'C': 1}

In [52]:
from sklearn.decomposition import PCA

pca = PCA(0.95)
x_pca = pca.fit_transform(x_scaled)
x_pca

array([[ 3.1127753 , -0.41658958,  0.66578215, ...,  0.18819508,
        -0.11003054,  0.27117526],
       [ 0.19020862, -1.07624669,  0.91867491, ...,  1.02192511,
        -0.23292103, -0.16634318],
       [ 1.63879275,  2.18185473,  0.41776913, ..., -0.59357507,
        -2.04145124,  0.13946001],
       ...,
       [-1.77715593, -1.47905475, -0.30823014, ...,  0.09497848,
         0.37862368,  0.12794198],
       [ 1.10463024,  0.20458484,  1.84982607, ...,  1.07153522,
         1.39743338,  0.34416985],
       [ 2.51254528, -0.47243606, -0.90466298, ...,  0.11362542,
        -0.06814383, -0.01807308]])

In [51]:
model=LogisticRegression(solver='liblinear',multi_class='auto',C=

In [53]:
model.fit(X_train,y_train)

LogisticRegression(C=1, solver='liblinear')

In [54]:
model.score(X_test,y_test)

0.8611111111111112

In [56]:
X_trainP, X_testP, y_trainP, y_testP = train_test_split(x_pca, y, test_size=0.2, random_state=30)

In [57]:
model.fit(X_trainP,y_trainP)

LogisticRegression(C=1, solver='liblinear')

In [58]:
model.score(X_testP,y_testP)

0.8666666666666667